### PR TITLE
invoice app using remoteStorage & Sockethub

### PR DESCRIPTION
**Pull request by silverbucket**
all the issues have been worked out, and sockethub is running as a public instance on my server (silverbucket.net) ... tested on my machine and everything seems to be working.

modal window still isnt closing. also, would be good to show some feedback when an email is sent?

### CODE REVIEW

**Comment by gr2m** [comment]
NICE! I'll check it out tomorrow! I've fixed the problem with the modal window already. And when the email is sent: just do an alert() I'd say

**Comment by gr2m** [comment]
Just gave it a try, it's not 100% solid, but neither is the Hoodie implementation ;-)

For example changes in one browser do not show up in the other until I sign out, sign back in and reload the page, can you confirm? Shall we make an issue?

**Comment by silverbucket** [comment]
Yes, that's due to us not making use of the onChange event. I will fix the documents module (so that it filters by the listing we requested). The one thing I'm not sure about is, during load the change event fires for every document, but we already getAll listing and populate the invoice list that way. So, we want to ignore the change events the first time around? Or just apply them anyway (there'd be no noticeable change I guess).... Maybe the second option is an OK option.

When the document listener function is fixed, we can also use 'delete' for when a document is deleted elsewhere, we remove it from the list.

**Comment by silverbucket** [comment]
I will submit a new pull request for those things when I get a chance.

**Comment by silverbucket** [comment]
Is Sockethub working OK for you? This is my first time running a public instance, so want to make sure that everything is working as expected so far. I have it connecting with SSL to my server silverbucket.net (otherwise I'd use sockethub.org, but don't yet have an SSL cert for it), it's behind an HAProxy instance, so I wanted to make sure there was no unexpected side effects.

**Comment by gr2m** [comment]
yeah, I tried it out and it worked like a charm :-) so cool!

**Pull request merged**
